### ISSUE TITLE
Add TypeScript and Bootstrap vue + convert to class-based components

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/CampHest#16]
### TODO
* [ ] `npm install typescript`
* [ ] `npm install bootstrap-vue`
* [ ] Make all components class based components
